name: Build and Push Docker to GHCR

description: |
  Build a Docker image and push it to GitHub Container Registry (ghcr.io) on push to main.

icon: check-square
categories: [deployment, container]

on:
  workflow_dispatch:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image name and version
        id: meta
        run: |
          IMAGE="ghcr.io/${{ github.repository_owner }}/my-app"
          VERSION=$(git describe --tags --always || echo "latest")
          echo "image=$IMAGE" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --push \
            -t ${{ steps.meta.outputs.image }}:${{ steps.meta.outputs.version }} \
            -t ${{ steps.meta.outputs.image }}:latest \
            .
